// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMCQCLv3Q3BC-DKolOrsuUlcyufC3GSM',
    appId: '1:943815010289:web:85dbb43c669a96ef47c650',
    messagingSenderId: '943815010289',
    projectId: 'agriculture-info-manage-system',
    authDomain: 'agriculture-info-manage-system.firebaseapp.com',
    storageBucket: 'agriculture-info-manage-system.appspot.com',
    measurementId: 'G-EEYFBQJM91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPRBXeRBSNCr9IMsrJIpOGzo1ZRRQlgw',
    appId: '1:943815010289:android:c73df72d672fccc147c650',
    messagingSenderId: '943815010289',
    projectId: 'agriculture-info-manage-system',
    storageBucket: 'agriculture-info-manage-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcGeHGxDSCFcKiWEWBB2IEH1dfegag1g',
    appId: '1:943815010289:ios:ca1868151bc01b6d47c650',
    messagingSenderId: '943815010289',
    projectId: 'agriculture-info-manage-system',
    storageBucket: 'agriculture-info-manage-system.appspot.com',
    androidClientId: '943815010289-e62m9btsf1hqrqmk2ol4be3hogjhusdu.apps.googleusercontent.com',
    iosClientId: '943815010289-7a5ln5q3quc8sjvrpj7o28di33f94okl.apps.googleusercontent.com',
    iosBundleId: 'com.example.aims',
  );
}
